server:  
  port: ${PORT:3333}

spring:  
  application:
    name: customer-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
      instances:
        - name: account-service
          servers: localhost:2222

#eureka:  
#  client:
#    serviceUrl:
#      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
      
ribbon:
  listOfServers: localhost:2222
#  eureka:
#    enabled: true